# Generated by Django 6.0.3 on 2026-04-13 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('tipo_entrega', models.CharField(choices=[('RETIRADA', 'Retirada'), ('ENTREGA', 'Entrega')], default='RETIRADA', max_length=20, verbose_name='Tipo de Entrega')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGENDADA', 'Agendada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Doador')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Doador',
                'verbose_name_plural': 'Doadores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='Horário')),
                ('tipo', models.CharField(choices=[('RETIRADA', 'Retirada'), ('ENTREGA', 'Entrega')], max_length=20, verbose_name='Tipo')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('doacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='bazar.doacao', verbose_name='Doação')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.AddField(
            model_name='doacao',
            name='doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='bazar.doador', verbose_name='Doador'),
        ),
    ]
