# Generated by Django 6.0.3 on 2026-04-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0003_doacao_inventario_fields_and_baixada'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='endereco_cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP de Retirada'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='endereco_cidade',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='endereco_complemento',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='endereco_logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='endereco_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
