# Generated by Django 6.0.3 on 2026-04-18 03:16

from django.db import migrations, models


def migrate_agendamento_address_to_doacao(apps, schema_editor):
    Agendamento = apps.get_model('bazar', 'Agendamento')

    for agendamento in Agendamento.objects.select_related('doacao').all():
        doacao = agendamento.doacao
        changed_fields = []

        if (not doacao.endereco_cep) and agendamento.cep_retirada:
            doacao.endereco_cep = agendamento.cep_retirada
            changed_fields.append('endereco_cep')

        if (not doacao.endereco_logradouro) and agendamento.endereco:
            doacao.endereco_logradouro = agendamento.endereco
            changed_fields.append('endereco_logradouro')

        if doacao.tipo_entrega == 'RETIRADA':
            fallback_values = {
                'endereco_cep': '00000-000',
                'endereco_logradouro': 'NAO INFORMADO',
                'endereco_numero': 'S/N',
                'endereco_bairro': 'NAO INFORMADO',
                'endereco_cidade': 'NAO INFORMADA',
                'endereco_uf': 'XX',
            }
            for field_name, fallback_value in fallback_values.items():
                if not getattr(doacao, field_name):
                    setattr(doacao, field_name, fallback_value)
                    changed_fields.append(field_name)

        if changed_fields:
            doacao.save(update_fields=sorted(set(changed_fields)))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0004_doacao_endereco_bairro_doacao_endereco_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='endereco_bairro',
            field=models.CharField(default='', max_length=120, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='endereco_cep',
            field=models.CharField(default='', max_length=9, verbose_name='CEP de Retirada'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='endereco_cidade',
            field=models.CharField(default='', max_length=120, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='endereco_complemento',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='endereco_logradouro',
            field=models.CharField(default='', max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='endereco_numero',
            field=models.CharField(default='', max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='endereco_uf',
            field=models.CharField(default='', max_length=2, verbose_name='UF'),
        ),
        migrations.RunPython(migrate_agendamento_address_to_doacao, noop_reverse),
        migrations.RemoveField(
            model_name='agendamento',
            name='cep_retirada',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='endereco',
        ),
        migrations.AddConstraint(
            model_name='doacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_entrega', 'RETIRADA'), _negated=True), models.Q(models.Q(('endereco_cep', ''), _negated=True), models.Q(('endereco_logradouro', ''), _negated=True), models.Q(('endereco_numero', ''), _negated=True), models.Q(('endereco_bairro', ''), _negated=True), models.Q(('endereco_cidade', ''), _negated=True), models.Q(('endereco_uf', ''), _negated=True)), _connector='OR'), name='retirada_endereco_obrigatorio'),
        ),
    ]
