# Generated by Django 6.0.3 on 2026-04-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0005_remove_agendamento_cep_retirada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doador',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
    ]
