# Generated by Django 6.0.3 on 2026-04-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0006_alter_doador_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='tamanho',
        ),
        migrations.AlterField(
            model_name='doacao',
            name='descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='nome_item',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item'),
        ),
    ]
